<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gravity</string>
	</array>
	<key>name</key>
	<string>Gravity</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.gravity</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.gravity</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.gravity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>string-interpolation</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.gravity</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\+</string>
							<key>name</key>
							<string>keyword.operator.gravity</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|in|or|isa|for|var|and|not|func|else|enum|case|null|file|lazy|super|break|while|class|const|event|_func|_args|struct|repeat|switch|return|public|static|extern|import|module|default|private|continue|internal|undefined)\b</string>
			<key>name</key>
			<string>keyword.reserved.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>string.boolean.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\w|[\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;])+(?=\s*\()</string>
			<key>name</key>
			<string>support.function.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;</string>
			<key>name</key>
			<string>keyword.operator.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*:)</string>
			<key>name</key>
			<string>meta.tag.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)\w+(?=\.|\s|,|;|\)|\?|\+|\-|=)</string>
			<key>name</key>
			<string>support.constant.gravity</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gravity</string>
	<key>uuid</key>
	<string>6A273AF0-EB4A-11E3-AC10-0800200C9A66</string>
</dict>
</plist>